nums=list(range(1,11))
print("The first three items in the list are:")
print(nums[:3])
print("Three items from the middle of the list are:")
print(nums[4:7])
print("The last three items in the list are:")
print(nums[-3:])
